# Test Bed for Code


In [2]:
import Simulation as sim
import GeometryUtils as geoUtils


from GeometryUtils import get_obstacleID_geometries

In [ ]:
path_to_urdf_obstacle = "models/obstacles_house_formation.urdf"
simulation = sim.SimulationEnvironment(path_to_urdf_obstacle, visualize=True)
simulation.connect_meshcat()
simulation.build_model()

sim.print_model_instances(simulation.plant)

print("Obstacle geometries:")
print(geoUtils.get_obstacle_geometries(simulation.plant))
print("Done")

simulation.compute_obstacles()


Run the cell below to see what the random workspace looks like!

In [1]:
## GPT-3 code
import numpy as np

def generate_faces(vertices):
    # Initialize an empty list to store the faces
    faces = []

    # Iterate over each vertex and construct triangles
    for i in range(len(vertices)):
        # Get three consecutive vertices
        v0 = vertices[i]
        v1 = vertices[(i + 1) % len(vertices)]
        v2 = vertices[(i + 2) % len(vertices)]

        # Calculate the normal vector of the triangle
        normal = np.cross(v1 - v0, v2 - v0)

        # Check if the normal vector is zero, indicating colinearity
        if not np.allclose(normal, 0):
            # Add the triangle to the list of faces
            faces.append([i, (i + 1) % len(vertices), (i + 2) % len(vertices)])

    # Convert the list of faces to a numpy array
    faces = np.array(faces).T

    return faces

# Example usage:
vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1]]).T
faces = generate_faces(vertices)
print("Resulting faces:", faces)


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [27]:
## Bing AI code
import numpy as np
from scipy.spatial import Delaunay

def create_triangles_from_vertices(vertices):
    """
    Creates minimal triangle faces from a set of vertices.

    Args:
        vertices (np.ndarray): An array of shape (3, N) representing N vertices.

    Returns:
        np.ndarray: An array of shape (3, M) representing M triangles (faces).
    """
    # Perform Delaunay triangulation
    tri = Delaunay(vertices.T)

    # Get the indices of the vertices forming each triangle
    faces = tri.simplices.T

    return faces

# Example usage
vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1]]).T
# vertices = np.array([[-0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5],
#                     [10. , 10. , 10. , 10. ,  8. ,  8. ,  8. ,  8. ],
#                     [1.5,  1.5,  0.5,  0.5,  0.5,  0.5,  1.5,  1.5]])
resulting_faces = create_triangles_from_vertices(vertices)

print("Resulting faces (triangle indices):")
print(resulting_faces)


QhullError: QH6154 Qhull precision error: Initial simplex is flat (facet 1 is coplanar with the interior point)

While executing:  | qhull d Qt Q12 Qc Qbb Qz
Options selected for Qhull 2019.1.r 2019/06/21:
  run-id 1958887482  delaunay  Qtriangulate  Q12-allow-wide  Qcoplanar-keep
  Qbbound-last  Qz-infinity-point  _pre-merge  _zero-centrum  Qinterior-keep
  Pgood  _max-width  1  Error-roundoff 2e-15  _one-merge 1.8e-14
  Visible-distance 1.2e-14  U-max-coplanar 1.2e-14  Width-outside 2.4e-14
  _wide-facet 7.3e-14  _maxoutside 2.4e-14

precision problems (corrected unless 'Q0' or an error)
      1 degenerate hyperplanes recomputed with gaussian elimination
      1 nearly singular or axis-parallel hyperplanes
      1 zero divisors during back substitute
      2 zero divisors during gaussian elimination

The input to qhull appears to be less than 4 dimensional, or a
computation has overflowed.

Qhull could not construct a clearly convex simplex from points:
- p3(v5):     0     0     1  0.45
- p4(v4):   0.5     0   0.5     1
- p2(v3):     1     0     1  0.91
- p1(v2):     1     0     0  0.45
- p0(v1):     0     0     0     0

The center point is coplanar with a facet, or a vertex is coplanar
with a neighboring facet.  The maximum round off error for
computing distances is 2e-15.  The center point, facets and distances
to the center point are as follows:

center point      0.5        0      0.5   0.5636

facet p4 p2 p1 p0 distance=    0
facet p3 p2 p1 p0 distance=    0
facet p3 p4 p1 p0 distance=    0
facet p3 p4 p2 p0 distance=    0
facet p3 p4 p2 p1 distance=    0

These points either have a maximum or minimum x-coordinate, or
they maximize the determinant for k coordinates.  Trial points
are first selected from points that maximize a coordinate.

The min and max coordinates for each dimension are:
  0:         0         1  difference=    1
  1:         0         0  difference=    0
  2:         0         1  difference=    1
  3:         0         1  difference=    1

If the input should be full dimensional, you have several options that
may determine an initial simplex:
  - use 'QJ'  to joggle the input and make it full dimensional
  - use 'QbB' to scale the points to the unit cube
  - use 'QR0' to randomly rotate the input for different maximum points
  - use 'Qs'  to search all points for the initial simplex
  - use 'En'  to specify a maximum roundoff error less than 2e-15.
  - trace execution with 'T3' to see the determinant for each point.

If the input is lower dimensional:
  - use 'QJ' to joggle the input and make it full dimensional
  - use 'Qbk:0Bk:0' to delete coordinate k from the input.  You should
    pick the coordinate with the least range.  The hull will have the
    correct topology.
  - determine the flat containing the points, rotate the points
    into a coordinate plane, and delete the other coordinates.
  - add one or more points to make the input full dimensional.


In [24]:
import numpy as np

def find_centroid(vertices):
    """Calculate the centroid of a set of 3D vertices assumed to be in a plane."""
    x = vertices[0, :]
    y = vertices[1, :]
    z = vertices[2, :]
    centroid = np.array([np.mean(x), np.mean(y), np.mean(z)])
    return centroid

def sort_vertices(vertices):
    """Sort vertices in counter-clockwise order based on their 2D projection."""
    centroid = find_centroid(vertices)
    angles = np.arctan2(vertices[1, :] - centroid[1], vertices[0, :] - centroid[0])
    return vertices[:, angles.argsort()]

def is_convex(a, b, c):
    """Return true if the triple is arranged in counter-clockwise order."""
    return (b[0] - a[0]) * (c[1] - a[1]) - (b[1] - a[1]) * (c[0] - a[0]) > 0

def point_in_triangle(pt, v1, v2, v3):
    """Check if point pt lies inside the triangle given by vertices v1, v2, v3."""
    def sign(p1, p2, p3):
        return (p1[0] - p3[0]) * (p2[1] - p3[1]) - (p2[0] - p3[0]) * (p1[1] - p3[1])

    d1 = sign(pt, v1, v2)
    d2 = sign(pt, v2, v3)
    d3 = sign(pt, v3, v1)

    has_neg = (d1 < 0) or (d2 < 0) or (d3 < 0)
    has_pos = (d1 > 0) or (d2 > 0) or (d3 > 0)

    return not (has_neg and has_pos)

def ear_clip(vertices):
    """Perform ear clipping algorithm to triangulate a simple polygon."""
    n = vertices.shape[1]
    indices = list(range(n))
    faces = []

    while len(indices) > 3:
        made_cut = False
        for i in range(len(indices)):
            prev_index = indices[i - 1]
            curr_index = indices[i]
            next_index = indices[(i + 1) % len(indices)]
            prev_vertex = vertices[:, prev_index]
            curr_vertex = vertices[:, curr_index]
            next_vertex = vertices[:, next_index]
            if is_convex(prev_vertex, curr_vertex, next_vertex):
                # Check if any other vertex is inside the triangle
                ear_found = True
                for other_index in indices:
                    if other_index not in [prev_index, curr_index, next_index]:
                        if point_in_triangle(vertices[:, other_index], prev_vertex, curr_vertex, next_vertex):
                            ear_found = False
                            break
                if ear_found:
                    faces.append([prev_index, curr_index, next_index])
                    indices.remove(curr_index)
                    made_cut = True
                    break
        if not made_cut:  # If no ears are found, try to force a cut as last resort
            faces.append([indices[0], indices[1], indices[2]])
            del indices[0]
            made_cut = True

    if len(indices) == 3:  # Add the last remaining triangle
        faces.append(indices)

    return np.array(faces).T

# Example usage:
vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1]]).T
# vertices = np.array([[-0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5],
#                     [ 9.5,  9.5,  9.5,  9.5,  8.5,  8.5,  8.5,  8.5],
#                     [ 2. ,  2. ,  0. ,  0. ,  0. ,  0. ,  2. ,  2. ]])

# vertices = vertices[::-1]
sorted_vertices = sort_vertices(vertices)
faces = ear_clip(sorted_vertices).T
print("Triangulated faces indices:\n", faces)




Triangulated faces indices:
 [[0 1 2]
 [1 2 3]]


In [ ]:
faces_ = np.array([[0, 1, 2],
                [1, 2, 3],
                [2, 3, 4],
                [3, 4, 5],
                [4, 5, 6],
                [5, 6, 7]]).T
np.array([[0, 1, 2],[ 3, 0, 2], 
          [0, 7, 3 ], [4, 3, 7], 
          [7, 6, 5], [4, 7, 5],
          [6, 1, 2], [5, 6, 2],
          [6, 1, 0], [7, 6, 0],
          [4, 5, 2], [3, 4, 2]]).T

In [31]:
import numpy as np
from scipy.spatial import ConvexHull

# Redefining data and method to triangulate a convex polyhedron using scipy's ConvexHull
vertices = np.array([[-0.5, 0.5, 0.5, -0.5, -0.5, 0.5, 0.5, -0.5],
                     [9.5, 9.5, 9.5, 9.5, 8.5, 8.5, 8.5, 8.5],
                     [2., 2., 0., 0., 0., 0., 2., 2.]]).T


vertices = np.array([[-0.5,  0.5,  0.5, -0.5, -0.5,  0.5,  0.5, -0.5],
                            [ 9.5,  9.5,  9.5,  9.5,  8.5,  8.5,  8.5,  8.5],
                            [ 2. ,  2. ,  0. ,  0. ,  0. ,  0. ,  2. ,  2. ]]).T

# vertices = np.array([[0, 0, 0], [1, 0, 0], [1, 0, 1], [0, 0, 1], [0, 1, 0]])
# Compute the convex hull to triangulate the polyhedron

print("vertice shape: ", vertices.shape)
hull = ConvexHull(vertices)
faces = hull.simplices.T

print("Triangulated faces indices:\n", faces)

vertice shape:  (8, 3)
Triangulated faces indices:
 [[3 3 7 7 7 7 5 5 5 5 5 5]
 [2 1 3 3 1 6 3 3 7 7 2 6]
 [1 0 0 4 0 1 2 4 4 6 1 1]]


<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f04667bf-32a3-4462-9e65-eda0faf36cb4' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>